census-instrumentation/opencensus-service

cmd/opencensusd/main.go
example/main.go
exporter/exporter.go
internal/internal.go

This commit contains an initial prototype for the exporter daemon
that can discovered via and endpoint file on the host.
The exporter looks for the endpoint file to see the availability
of the daemon and exports if it is running.
Exporter daemon will allow OpenCensus users to export
without having to link a vendor-specific exporter in their final
binaries. We are expecting the prototype exporter is going to
be implemented in every language and registered by default.

Initial commit of the exporter daemon and its Go exporter

---

cmd/opencensusd/main.go
exporter/exporter.go
internal/internal.go

It allows us to extend what else we are going to store
as metadata in the file.
Fixes #5.

Make endpoint file a JSON

---

spanreceiver/spanreceiver.go

An interface `SpanReceiver` that receives *tracepb.Span instances
and sends back an acknowledgement and an error.
The return signature is `(*Acknowledgement, error)` because it
would useful to return to callers information about how many spans
were successful, errors that were encountered, allowing for batches
of spans to be written like we would with `io.Write`. This will allow
callers to retry, report success and failure rates too.
Fixes #30

spanreceiver: define SpanReceiver interface

---

translator/trace/protospan_to_spandata.go
translator/trace/protospan_to_spandata_test.go

Provides a function to translate *tracepb.Span
into *go.opencensus.io/trace.SpanData
Updates #26

translator/trace: ProtoSpanToOCSpanData

---

interceptor/opencensus/doc.go
interceptor/opencensus/opencensus.go
interceptor/opencensus/opencensus_test.go
interceptor/opencensus/options.go

Implemented the OpenCensus interceptor that
opencensus-agent-exporters in the various languages
will send traces to. It is initialized with at least
a non-nil spanreceiver.SpanReceiver.
I also added an end-to-end test to ensure that traces
are properly proxied to the spanreceiver.SpanReceiver.
Fixes #32

trace/interceptor: implement OpenCensus interceptor

---

cmd/ocagent/exporterparser/datadog.go
cmd/ocagent/exporterparser/exparser.go
cmd/ocagent/exporterparser/stackdriver.go
cmd/ocagent/exporterparser/zipkin.go
cmd/ocagent/main.go

With this change, cmd/ocagent now adheres
to the new protocol and currently runs
the OpenCensus interceptor while exporting
received spans to the various and previously
already created YAML configured exporters such as:
* Stackdriver Tracing
* DataDog
* Zipkin
which are statically imported.
Now any program that has an ocagent-exporter
can send traces to this service. The service's
OpenCensus Interceptor Port can be configured by
```shell
ocagent -oci-port=<value>
```
which by default is `55678`
After this change we can add both more trace exporters
and more trace interceptors.
Essentially this can be our v0.0.1 of the new trace
agent/service.

cmd/ocagent: retrofitted with new protocol

---

exporter/plugins.go
exporter/plugins.md

Added the TraceExporterPlugin interface of the type
```go
type TraceExporterPlugin interface {
TraceExportersFromConfig(blob []byte, configType ConfigType) ([]TraceExporter, error)
Stop(context.Context) error
}
```
as well as a guide and sample of an end-to-end written plugin.
This is the interface and introduction phase of fixing the
target issue. Actual plugin into `cmd/ocagent` will come
in the final change.
Updates #47

exporter: add Plugins interface as well as guide

---

cmd/ocagent/main.go
interceptor/opencensus/observability_test.go
interceptor/opencensus/opencensus.go
interceptor/opencensus/opencensus_test.go
interceptor/opencensus/trace_interceptor.go
internal/observability.go

Instrument interceptor/opencensus with stats to record
the number of received spans. This is accomplished by
a helper to process spans that sends over spans even
if the number of spans is 0. Also record with tag_key
"opencensus_interceptor" whose value is the name
of the respective interceptor.
The test to ensure that 0 length spans are also added
is currently disabled because:
* Issue https://github.com/census-instrumentation/opencensus-go/issues/862
is not yet implemented which requests that the OpenCensus-Go
stats worker provide a method Flush to flush all data. Without
it, metrics will contain stale data from previous tests.
Add tests to lock-in this behavior.
Updates #63

interceptor/opencensus: record number of received spans

---

README.md
cmd/ocagent/config.go
cmd/ocagent/config.yaml
cmd/ocagent/main.go

Use the config.yaml file to configure the OpenCensus
interceptor listener's address, instead of using commandline flags.
This is because all the other configurations are performed
using the config.yaml file so an extra option is just confusing.
The default port to run on is 55678 if unspecified, but otherwise
YAML parseable by key `opencensus_interceptor`, and then using the
field name `address`. For example:
```yaml
opencensus_interceptor:
address: ":55777"
```
and when run with
```shell
ocagent
```
which will then produce:
```shell
2018/10/08 16:36:47 Running OpenCensus interceptor as a gRPC service at "localhost:55777"
```
Fixes #23

cmd/ocagent: OpenCensus interceptor bind address configurable via config.yaml

---

cmd/ocagent/config.go
cmd/ocagent/main.go

- Shorter names for variables and types.
- Print flag values instead of pointer values.
- Use -config instead of -exporters-yaml because config contains more than exporters.

Minor readability improvements

---

README.md

Instructions of how to build binaries properly as
well as how to build a Docker image.
By "properly" I mean, a binary that contains the GitHash
of what code was used to build the ocagent binary but
also how to cross-compile and create other binaries using
the provided helper script.

README: add section for building binaries and Docker image

---

interceptor/opencensus/opencensus.go

I think there is an improper use of closure between [opencensus.go#L104](https://github.com/census-instrumentation/opencensus-service/blob/master/interceptor/opencensus/opencensus.go#L104) and [opencensus.go#L113](https://github.com/census-instrumentation/opencensus-service/blob/master/interceptor/opencensus/opencensus.go#L113)
```golang
processReceivedSpans := func(ni *commonpb.Node, spans []*tracepb.Span) {
// Firstly, we'll add them to the bundler.
if len(recv.Spans) > 0 {
bundlerPayload := &spansAndNode{node: ni, spans: recv.Spans}
traceBundler.Add(bundlerPayload, len(bundlerPayload.spans))
}
// We MUST unconditionally record metrics from this reception.
spansMetricsFn(ni, recv.Spans)
}
```
This PR makes code changes as follow:
```golang
processReceivedSpans := func(ni *commonpb.Node, …
```

fixup improper closure usage

---

interceptor/opencensus/observability_test.go

`go test -race` produces a slowdown in the program by
between 2-20X yet this test depends on precise timings
in the OpenCensus-Go stats worker. Disable it as it is
very flaky and causing unrelated failures in PRs.

interceptor/opencensus: skip TestEnsureRecordedMetrics

---

interceptor/opencensus/opencensus_test.go
internal/internal.go
translator/trace/protospan_to_spandata_test.go

Move the common helper TimeToTimestamp to internal
instead of duplicating its functionality allover
the repository. It is needed for implementing other
interceptors.

all: move helper TimeToTimestamp to internal

---

interceptor/opencensus/opencensus_test.go

This test depends on precise timings but -race slows down
the program by 2-20X hence we've received flakes from this test.
Fixes #95

interceptor/opencensus: temporarily disable TestOCInterceptor_endToEnd

---

exporter/exporterparser/datadog.go
exporter/exporterparser/exparser.go
exporter/exporterparser/stackdriver.go
exporter/exporterparser/zipkin.go
internal/observability.go

After each exporter has exported spans, record the
number of spans exported with tag:
"opencensus_exporter": <name>
Updates #64

exporter/exporterparse: metrics for exported spans

---

exporter/exporterparser/datadog.go
exporter/exporterparser/stackdriver.go

[Relevant issue](https://github.com/census-instrumentation/opencensus-service/issues/113)
Fix that updates the `enableTraces` field in the parser for the Stackdriver and Datadog config. I was not able to find other places that needed updating.

Update Stackdriver configuration parser enableTraces field

---

README.md

The README was stale in regards to the Stackdriver
configuration flags in YAML.
This change updates the README to indicate that
the correct flag is `enable_traces` and not `enableTraces`
Fixes #113
Supersedes #114

README: fix Stackdriver trace enabling flag

---

README.md
cmd/ocagent/config.go
cmd/ocagent/config.yaml
cmd/ocagent/main.go
example/main.go
interceptor/opencensus/opencensus.go

Added zPages as the diagnostic helper for the overall
ocagent process itself #inception
By default the zPages run at ":55679/debug". They can be
disabled in the config.yaml file by using the attribute
`disabled`
```yaml
zpages:
disabled: true
port: 8888
```
Also added as an attribute the number of exported spans
for every internal interceptor span.
Fixes #83

cmd/ocagent: added zPages for overall ocagent process

---

interceptor/opencensus/opencensus.go
interceptor/opencensus/opencensus_test.go
interceptor/opencensus/options.go

Given that the package name is already ocinterceptor, using
OCInterceptor as a prefix for the type name is now unnecessary.
That naming was because the package was one of the first ones
to be added. Now that the packaging is mature this has come up
as a better suggestion to remove that unnecessary prefix.
Fixes #88

interceptor/opencensus: remove redundant OCInterceptor prefix

---

README.md
cmd/ocagent/config.go
cmd/ocagent/config.yaml
exporter/exporterparser/datadog.go
exporter/exporterparser/stackdriver.go
exporter/exporterparser/zipkin.go

Categorize namespaces of each item into:
- exporters
- interceptors
- zpages
which aesthetically looks nicer than the original but also
gives users better context and control over what the agent
does.
For example here is the new configuration file:
```yaml
interceptors:
opencensus:
address: "127.0.0.1:55678"
exporters:
stackdriver:
project: "project-id"
enable_tracing: true
zipkin:
endpoint: "http://localhost:9411/api/v2/spans"
datadog:
enable_tracing: false
zpages:
port: 55679
```
Fixes #90

config.yaml: categorize and reorganize YAML file

---

interceptor/opencensus/opencensus.go
interceptor/opencensus/opencensus_test.go
interceptor/opencensus/options.go
interceptor/opencensus/trace_interceptor.go

OCOption is redundant within the package ocinterceptor,
hence fix that with a rename to Option.
Fixes #87

interceptor/opencensus: rename OCOption to Option

---

interceptor/interceptor.go
metricreceiver/metricreceiver.go
metricsreceiver/metricsreceiver.go

Updates https://github.com/census-instrumentation/opencensus-service/issues/99.
Fixes https://github.com/census-instrumentation/opencensus-service/issues/20.
From https://github.com/census-instrumentation/opencensus-go/issues/940#issuecomment-431929219, OC-Go is going to use the proto gen-go files for `Metrics` implementation, so I think we can start adding the metric receiver and interceptor interfaces now. Note that although the `Metrics` proto hasn't been finalized or released, any future changes will be backwards-compatible, so we should be able to use the `metricpb.Metric` for now.
Next step: add OpenCensus `metric_interceptor`, which depends on [metrics_service.proto](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/agent/metrics/v1/metrics_ …

interceptor: start adding metric receiver and interceptor.

---

README.md

Fixes https://github.com/census-instrumentation/opencensus-service/issues/134. 
This matches the current design of Go and Java agent exporters.

README: Add a paragraph about Library retries.

---

.travis.yml
Makefile
interceptor/zipkin/trace_interceptor_test.go

This is very minimalistic: it adds a Makefile and switches Travis
to use it. The Makefile tries to do the same things as the previous
script (golint is not enabled yet since it is breaking the build).

Add a minimal Makefile and set Travis to use it

---

.gitignore
Makefile
cmd/ocagent/Dockerfile
cmd/ocagent/config.go
cmd/ocagent/main.go
cmd/occollector/Dockerfile
cmd/occollector/main.go
exporter/exporterparser/zipkin_test.go

* Adds the scratch docker for agent and collector
* Opportunistically change some close functions to close the server 
instead of the listener that they depend on (a somewhat cleaner shutdown),
the servers close take care of closing the listeners

Add docker scratch for agent and collector

---

cmd/ocagent/config.go

The logical conflict test was triggering a false positive in case a Zipkin exporter was enabled but a Zipkin interceptor was not.
Without the interceptor enabled, the test ran against the default Zipkin endpoint as if it was configured to run under that default Zipkin endpoint.
The test now checks if both Exporter and Interceptor are enabled before testing the endpoints.

fix the logical conflict test for zipkin

---

go.mod
go.sum
interceptor/zipkin/proto_parse_test.go
interceptor/zipkin/trace_interceptor.go
interceptor/zipkin/trace_interceptor_test.go
internal/internal_test.go

interceptor/zipkin: add logic to parse from Protobuf
Can now intercept Zipkin Protobuf spans that are
sent to a Zipkin server.
The ZipkinInterceptor multiplexes on the "Content-Type"
header, checking if the value set is "application/x-protobuf"
otherwise fallback to try parsing as JSON.
Fixes #154
Spawned https://github.com/openzipkin/zipkin-go/issues/87
Waiting on https://github.com/openzipkin/zipkin-go/pull/88

interceptor/zipkin: add logic to parse from Protobuf

---

internal/internal.go
translator/trace/jaegerthrift_to_protospan.go
translator/trace/jaegerthrift_to_protospan_test.go

translator/trace/jaeger: conservative allocations for only existent fields
* Only allocate TraceID and SpanID iff they are non-nil lest we'll
consume 8/16 bytes for every span which becomes quite expensive
* Also retrieve "status.code" and "status.message" as the Jaeger exporter
from OpenCensus sends those
* Avoid creating an attributes map if attributes don't exist and
let go of the `make(map[<K>]<V>, size_hint)` idiom as it prevents
us from being able to detect if values were added to the attributes map
* Added in-code conversion tests to ensure fidelity preservation
* Translate "message" in logs/tags to a description value
Noticed while rolling out the Jaeger receiver/interceptor.
Fixes #187
Fixes #188
Fixes #189
Fixes #190

translator/trace/jaeger: conservative allocations for only existent fields

---

README.md
cmd/ocagent/config.go
cmd/ocagent/main.go
go.mod
go.sum
receiver/jaeger/trace_receiver.go
receiver/jaeger/trace_receiver_test.go

Jaeger collector running on HTTP and Thrift implemented.
The configuration can be set as:
```yaml
receivers:
jaeger:
collector_http_port: 14268
collector_thrift_port: 14267
```
Fixes #153

receiver/jaeger: implement and hookup Jaeger receiver

---

receiver/opencensus/ocmetrics/opencensus_test.go

~Fixes~ Updates https://github.com/census-instrumentation/opencensus-service/issues/136.
Note currently we don't have E2E tests for metrics receiver, since ocagent-exporter hasn't added support for metrics service.

receiver/ocmetrics: add tests on ocmetrics receiver.

---

cmd/ocagent/main.go
exporter/exporterparser/zipkin_test.go
internal/collector/zipkin/receiver.go
receiver/zipkin/trace_receiver.go
receiver/zipkin/trace_receiver_test.go

Moved the server starting logic to the receiver and updated
New to
New(address string) (*ZipkinReceiver, error)
instead of
New(spansink.Sink) (*ZipkinReceiver, error)
This change ensures that after invoking New all the user
has to do is then just invoke:
zr.StartTraceReception(context.Context, spansink.Sink) error
and then for cleanup
defer zr.StopTraceReception(context.Context)
Fixes #212

receiver/zipkin: consolidate server starting to receiver

---

exporter/trace_exporter.go
internal/collector/processor/exporter_processor.go
internal/collector/processor/processor_to_sink.go
receiver/end_to_end_test.go
receiver/jaeger/trace_receiver.go
receiver/jaeger/trace_receiver_test.go
receiver/opencensus/ocmetrics/opencensus.go
receiver/opencensus/ocmetrics/opencensus_test.go
receiver/opencensus/octrace/opencensus.go
receiver/opencensus/octrace/opencensus_test.go
receiver/receiver.go
receiver/zipkin/trace_receiver.go
receiver/zipkin/trace_receiver_test.go

Fixes https://github.com/census-instrumentation/opencensus-service/issues/182.
Updates https://github.com/census-instrumentation/opencensus-service/issues/215. 
~~Blocked by https://github.com/census-instrumentation/opencensus-service/pull/223.~~

receiver: use TraceData and MetricsData in receivers.

---

exporter/metrics_exporter.go

Fixes https://github.com/census-instrumentation/opencensus-service/issues/100.
While the actual implementation of metrics exporters depends on the metrics data model in OC-Go, we can add the exporter interface first.

metrics/exporter: define MetricsExporter interface.

---

exporter/exporterparser/zipkin.go
exporter/exporterparser/zipkin_test.go

Safely retrieve the servicename for the remoteEndpoint if no
endpoints were sent in the payload hence a nil Node.
A reduction of PR #229 and originally @pjanotti's endeavor.
Fixes #230

exporterparser/zipkin: safely retrieve remoteEndpoint serviceName

---

cmd/ocagent/config.go
cmd/ocagent/config_test.go

The Zipkin logical conflict detection had 2 errors:
a) By mistake, it resolved the receiver{Host, Port}
from the exporterHostPort address
b) During IP resolution to check say if "localhost" and "//zipkin"
were the same, if the results were the same, the ports weren't
checked for equivalence hence if we had:
"localhost:9410" and "127.0.0.1:9411"
it would incorrectly report a logical conflict.
Added a regression test as well.
Fixes #233

cmd/ocagent: fix Zipkin logical conflict detection typo

---

go.mod
go.sum
internal/testutils/test_utils.go
receiver/jaeger/trace_receiver_test.go
translator/trace/jaegerthrift_to_protospan.go
translator/trace/jaegerthrift_to_protospan_test.go
translator/trace/protospan_to_jaegerthrift.go
translator/trace/protospan_to_jaegerthrift_test.go
translator/trace/testdata/ocproto_batch_02.json
translator/trace/testdata/thrift_batch_no_binary_tags_01.json
translator/trace/testdata/thrift_batch_no_binary_tags_02.json

Add a translator from OC-Proto to Jaeger Thrift.
As usual there are some questions about the translation,
they should be marked with TODOs but we may want to
follow up with some discussion about the general rules in
translation (e.g.: preserve key-value info even if it maps to
some property).

OC Proto to Jaeger Thrift translation

---

cmd/ocagent/main.go
internal/config/config.go

For now before any OpenCensus Metrics exporter is created, just
hook it up. This will allow applications such as the OpenCensus-PHP
stats backend to send content.
Fixes #216

cmd/ocagent: add OpenCensus Metrics receiver + noopMetricsSink

---

cmd/ocagent/main.go
receiver/opencensus/opencensus.go

Provide a Start method on the OpenCensus receiver to allow registering
all services before running the gRPC server.
Unfortunately gRPC's RegisterService doesn't return an error so
it has no choice but to Fatalf as per
https://github.com/grpc/grpc-go/blob/ca62c6b92c334f52c7e48b7cbf624f3b877fb092/server.go#L408-L410
By design, in Go we cannot catch a .Fatalf that invokes os.Exit(code)
so even a test is worthless to test this.
Fixes #243

receiver/opencensus: provide a Start method for both Trace and Metrics

---

Makefile
README.md

Updates https://github.com/census-instrumentation/opencensus-service/issues/218.
Set env var `GO111MODULE` to on before make agent/collector. Otherwise users will get errors like https://github.com/census-instrumentation/opencensus-service/issues/218.
Also reported offline by @rghetia.

README: Update usage commands.

---

receiver/jaeger/trace_receiver.go

Enable the TChannel receiver for Jaeger.
@odeke-em per our earlier conversation I don't have bandwidth rightnow to write a test for it. I also see that is going to conflict with the PR that you have open, either one can go first since the fix is simple. It will be good if we get this in before we cut another version.
Fixes #245

Receive jaeger-agent tchannel on port 14267

---

cmd/ocagent/main.go
go.mod
go.sum
internal/collector/jaeger/receiver.go
receiver/jaeger/jaeger_agent_test.go
receiver/jaeger/trace_receiver.go

* Update receiver/jaeger.New to take in a Configuration
that now allows specifying the Jaeger agent UDP ports
* Separated out startCollector and startAgent helpers
for the Jaeger receiver
* Agent now runs on UDP ports:
+ Thrift Compact: by default 6831
+ Thrift Binary: by default 6832
+ Agent server: by default 5778

receiver/jaeger: Jaeger Agent running on UDP ports

---

Makefile
build_binaries.sh
internal/version/version.go

As we complete milestones we plan to cut versions. Today, this requires
editing two separate files and committing them. Instead, default to a
version of "latest" and allow the version to be passed as part of
build_binaries or make.
Thought process here is that if a user builds from source they will have latest and the githash is included as well. Today, a hard-coded version is included, which can be confusing as changes may have been made since the release. Long term, we should consider having dedicated branches for stable releases (and could hard-code the version into these branches if desired). In addition, we should discourage building from source if possible and provide binaries as well as Docker images.

Add dynamic support for VERSION and default to latest

---

go.mod
receiver/zipkin/proto_parse_test.go
receiver/zipkin/trace_receiver.go
receiver/zipkin/trace_receiver_test.go
translator/trace/testdata/zipkin_v1_multiple_batches.json
translator/trace/testdata/zipkin_v1_single_batch.json
translator/trace/zipkinv1_to_protospan.go
translator/trace/zipkinv1_to_protospan_test.go

Fixes #250 
Add a trace translator from Zipkin V1 to OC proto.
Per ealier dicussion we just need to support JSON,
this gets OC service working with current Envoy tracing
for Zipkin.

Add support to Zipkin V1

---

README.md
cmd/occollector/app/collector/collector.go
internal/collector/processor/processor.go
internal/collector/processor/queued_processor.go
internal/collector/telemetry/telemetry.go

This change adds a Prometheus endpoint using OC to provide metrics
to the collector. There are settings to control the level and port
in which the metrics are exposed. The main metrics added for now
are in the queued exporters.

Add basic telemetry to collector

---

cmd/occollector/app/collector/collector.go

Previously all supported trace receivers (opencensus, zipkin, jaeger)
were disabled by default. This change enables the opencensus trace
receiver by default.
Fixes #259

Opencensus trace receiver should be enabled by default

---

README.md
cmd/occollector/app/collector/collector.go

healthcheck runs by default on port 13133 and is configurable with --health-check-http-port <port_num>.
Issue:#290
Testing Done: manually (port is configurable, endpoint curl-able, re-bind to port logs descriptive error)

Add healthcheck http server to collector service

---

cmd/ocagent/main.go
cmd/occollector/app/collector/collector.go
exporter/exporterparser/datadog.go
exporter/exporterparser/jaeger.go
exporter/exporterparser/kafka.go
exporter/exporterparser/opencensus.go
exporter/exporterparser/stackdriver.go
exporter/exporterparser/zipkin.go
exporter/exporterparser/zipkin_test.go
exporter/metrics_exporter.go
internal/config/config.go

ExportersFromYAMLConfig now returns metricsExporters
if the underlying code implements exporter.MetricsExporter.

all: accept MetricsExporters by implementation

---

.travis.yml
CONTRIBUTING.md
Dockerfile
README.md
build_binaries.sh
go.sum

I was in contact with someone trying to build the repo and his golang was a new install (via brew). So he hit the same issue as Travis w/ go 1.11.4 (see https://github.com/census-instrumentation/opencensus-service/pull/272): invalid checksum. 
The problem for us is that the recommendation for this issue is to remove the old checksum, this fixes the build for go 1.11.4. However, any previous go version is going to re-introduce the incorrect checksums (I tested only with go 1.11.1). So if we merge this change and don't upgrade go to 1.11.4 on our boxes we are going to keep getting a modified go.sum (re-introducing the wrong checksums), which is fine as long as people are aware of the issue and don't commit the go.sum - in other words if this PR is merged any changes to go.mod/go.sum need to …

Remove broken checksums now caught by go 1.11.4

---

translator/trace/testdata/zipkin_v1_multiple_batches.json
translator/trace/testdata/zipkin_v1_single_batch.json
translator/trace/zipkinv1_to_protospan.go
translator/trace/zipkinv1_to_protospan_test.go

If we received a span with no annotations, there would be a nil panic
due to parsedAnnotations being nil. This fixes that.
Testing Done: unit test added

Fix nil pointer panic zipkinv1

---

cmd/ocagent/main.go
internal/collector/opencensus/receiver.go

Due to issue https://github.com/census-instrumentation/opencensus-service/issues/287
these are not providing any useful information. Disabling them for now.

Temporarily disabling gRPC views for OC receiver

---

exporter/exporterparser/prometheus.go
exporter/exporterparser/prometheus_test.go

An embarassing crash would occur if in YAML, exporters were specified
and perhaps the Prometheus clause was started but had no content e.g.
```yaml
exporters:
prometheus:
```
This change fixes that by explicitly returning nil early, but also
added a test to ensure we never regress.

exporter/prometheus: fix nil deference when no Prometheus exporter

---

cmd/ocagent/main.go
go.mod
go.sum
internal/config/config.go
receiver/opencensus/opencensus.go
receiver/opencensus/opencensus_test.go
receiver/opencensus/options.go

This adds a new `cors_allowed_origins` YAML config parameter to the `opencensus` receiver config block, which, if specified will allow HTTP clients to write to the trace grpc-gateway using CORS with the specified list of origins (wildcards can be used to match all origins or arbitrary origin substrings).
This will help with development of [opencensus-web](https://github.com/census-instrumentation/opencensus-web).

Add CORS option for OC Receiver grpc-gateway

---

receiver/README.md

This documents how to write traces to the OpenCensus agent OpenCensus receiver using HTTP/JSON.

Add section HTTP/JSON doc section for OC receiver

---

translator/trace/protospan_to_jaegerthrift.go
translator/trace/protospan_to_jaegerthrift_test.go

Enforcing that conversion from OC proto to Jaeger always ends with a
non-nil Process.
Fix #332

Jaeger requires non-nil Process

---

go.mod
go.sum

Bring in fix
https://github.com/orijtech/prometheus-go-metrics-exporter/pull/2
which sanitizes tag keys, like the OpenCensus Prometheus Go exporter
does.

go.{mod, sum}: update Prometheus Metrics exporter

---

cmd/ocagent/main.go
cmd/occollector/app/builder/builder.go
cmd/occollector/app/builder/builder_test.go
cmd/occollector/app/builder/testdata/receivers_disabled.yaml
cmd/occollector/app/builder/testdata/receivers_enabled.yaml
cmd/occollector/app/collector/receivers.go
go.mod
go.sum
internal/collector/zipkin/scribe/receiver.go
internal/config/config.go
receiver/zipkin/scribe/scribe_receiver.go
receiver/zipkin/scribe/scribe_receiver_test.go
translator/trace/zipkinv1_thrift_to_protospan.go
translator/trace/zipkinv1_thrift_to_protospan_test.go

Fix #338 
Adds support to zipkin-scribe. While this is zipkin it uses a different protocol (other are all over http), so this becomes a different receiver "zipkin-scribe" that can be enabled separately from normal zipkin. It adds a reference to a repo with the thrift generated files for Scribe protocol (the project in question uses the same version of thrift currently used in oc-service, an old one to match usage in some Jaeger references), the repo is https://github.com/Omnition/scribe-go we can move it later if we want (we can't simply add the files to this repo because them we need to subject the generated files to the same gofmt rules, etc).

Add a "zipkin-scribe" receiver

---

cmd/ocagent/Dockerfile

While testing Stackdriver Export from the Docker image I ran into TLS errors. The agent image lacked the required ca-certificates.

update Dockerfile to include ssl certs (needed for Stackdriver exporter)

---

translator/trace/testdata/zipkin_v1_local_component.json
translator/trace/testdata/zipkin_v1_thrift_local_component.json
translator/trace/zipkinv1_thrift_to_protospan_test.go
translator/trace/zipkinv1_to_protospan.go
translator/trace/zipkinv1_to_protospan_test.go

The LOCAL_COMPONENT key is used to express the "component or namespace of a local span" in Zipkin V1. This should be used as a fallback for service name if other information is not available for the span.
The LOCAL_COMPONENT, if available, is one of the binary annotations on the span. This change tries to capture it when processing the binary annotations, but, only uses it if none of the other sources for service name is available.
Opportunistically adding equivalent test to Zipkin V1 Thrift that already handles LOCAL_COMPONENT correctly.
Fix #352

ZipkinV1 JSON Receiver: handle LOCAL_COMPONENT binary annotation

---

internal/config/config.go
internal/config/config_test.go

An embarrasing non-defensive nil dereference if
Config.Receivers.OpenCensus was nil
then either of:
* CanRunOpenCensusTraceReceiver
* CanRunOpenCensusMetricsReceiver
were invoked.
Fixes #377

internal/config: fix nil OpenCensus receiver dereference

---

receiver/opencensus/opencensus.go
receiver/opencensus/opencensus_test.go

If an unstarted OpenCensus receiver was Stop()-ed, it would
undefensively invoke .serverHTTP.Close()
which would cause a nil dereference panic, moreover in situations
where only unrelated receivers were explicitly started.
Fixes #379

receiver/opencensus: fix crash on unstarted receiver.Stop

---

Makefile

Adding a timeout to tests to help cache any test that maybe deadlocking with certain frequency.
This is related to #375

Makefile: add a timeout to tests

---

translator/trace/zipkinv1_thrift_to_protospan_test.go
translator/trace/zipkinv1_to_protospan_test.go

Internally the function being tested uses a map to generate the slice with the translation results, however, the order is not deterministic and some runs fail. There are just two elements on the translated results but to make clear the expectation of the test this change uses sort.Slice function to achieve the desired order.

Fix flaky test for Zipkin LOCAL_COMPONENT handling

---

README.md
example/main.go
exporter/exporterparser/aws_xray.go
exporter/exporterparser/aws_xray_test.go
go.mod
go.sum
internal/config/config.go

Added AWS X-Ray as a Trace exporter.
It shards exporters by service-name that's
retrieved by each Trace batch's Node.
With this sample configuration YAML file:
```yaml
receivers:
opencensus:
address: "localhost:55678"
exporters:
aws-xray:
default_service_name: "ocagent"
version: "latest"
buffer_size: 200
```
and obviously AWS credentials in your environment,
it will export to AWS X-Ray.
Fixes #241

exporters: enable AWS X-Ray Trace exporter

---

README.md
exporter/exporterparser/honeycomb.go
go.mod
go.sum
internal/config/config.go

Add Honeycomb.io as a trace exporter.
This exporter is based off OpenCensus-Go trace.Exporter.
However, I shall file an issue or firstly page them to
ask them to implement an OpenCensus-Proto trace Exporter.
This change currently imports the work from:
https://opencensus.io/exporters/supported-exporters/go/honeycomb/
or succinctly
https://github.com/honeycombio/opencensus-exporter
A sample YAML file is:
```yaml
receivers:
opencensus:
address: "localhost:55678"
exporters:
honeycomb:
write_key: "739769d7-e61c-42ec-82b9-3ee88dfeff43"
dataset_name: "dc8_9"
```
Fixes #398

exporter: add Honeycomb.io

---

internal/collector/processor/nodebatcher/node_batcher_test.go

internal/collector/processor/nodebatcher/node_batcher_test.go:242:3: Errorf format %d has arg sender.spansReceivedByName of wrong type map[string]*github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1.Span

Fix format error in tests.

---

exporter/exporterparser/aws_xray.go
exporter/exporterparser/datadog.go
exporter/exporterparser/exparser.go
exporter/exporterparser/honeycomb.go
exporter/exporterparser/jaeger.go
exporter/exporterparser/kafka.go
exporter/exporterparser/stackdriver.go
exporter/exporterparser/zipkin.go

Update the OpenCensus Proto TraceData
to OpenCensus-Go SpanData translator by:
* Name from:
"exportSpans"
to
"ocProtoSpansToOCSpanDataInstrumented"
to make it more intuitive but also declare
its intentions and add a reminder that we
should get vendors to start using OpenCensus Proto
* Added tracing for each export with a span that'll
record the errors and number of spans

exporter/exporterparser/all: update SpanData translator

---

exporter/awsexporter/aws_xray.go
exporter/awsexporter/aws_xray_test.go
exporter/datadogexporter/datadog.go
exporter/exporterparser/exparser.go
exporter/honeycombexporter/honeycomb.go
exporter/jaegerexporter/jaeger.go
exporter/kafkaexporter/kafka.go
exporter/opencensusexporter/opencensus.go
exporter/prometheusexporter/prometheus.go
exporter/prometheusexporter/prometheus_test.go
exporter/stackdriverexporter/stackdriver.go
exporter/zipkinexporter/zipkin.go
exporter/zipkinexporter/zipkin_test.go
internal/config/config.go
internal/config/config_test.go

With this change we split a large package exporterparser (in terms of dependencies) and make sure that we don't download the entire internet if depend on one of the exporters. 
Updates https://github.com/census-instrumentation/opencensus-service/issues/369

Move every exporter in it's own directory.

---

internal/collector/processor/nodebatcher/metrics.go
internal/collector/processor/queued/queued_processor.go
internal/collector/telemetry/process_telemetry.go

Count -> Sum changes are because count is the aggregation that counts the number of recorded measurements not the sum of the recorded values. In the current case this should be the same.
For process telemetry the TotalAlloc and CPUSeconds are exported as cumulative data so they need to use LastValue, unfortunately they will be exported as gauges even though they are cumulative values (this is unfortunately, but when metrics package will be done in Go we should use that).

Fix some of the stats exported.

---

cmd/occollector/app/collector/processors.go
exporter/exporterhelper/common.go
exporter/exporterhelper/common_test.go
exporter/exporterhelper/constants.go
exporter/exporterhelper/metricshelper.go
exporter/exporterhelper/metricshelper_test.go
exporter/exporterhelper/tracehelper.go
exporter/exporterhelper/tracehelper_test.go
exporter/loggingexporter/logging_exporter.go
exporter/loggingexporter/logging_exporter_test.go
exporter/opencensusexporter/opencensus.go
observability/observability_test.go
observability/observabilitytest/observabilitytest.go
observability/observabilitytest/observabilitytest_test.go
receiver/end_to_end_test.go
receiver/opencensusreceiver/octrace/observability_test.go

Only Logging and OpenCensus exporters changed in this PR, I will update all the others in a followup PR.

Add exporterhelper to wrap all exporters with observability.

---

receiver/opencensusreceiver/opencensus_test.go

Fixes https://github.com/census-instrumentation/opencensus-service/issues/492.
Test failure has been fixed with https://github.com/census-instrumentation/opencensus-service/pull/501 and https://github.com/census-instrumentation/opencensus-service/pull/506.

receiver/opencensus: Restore gRPC Gateway test.

---

Makefile
go.mod
receiver/jaegerreceiver/jaeger_agent_test.go
receiver/jaegerreceiver/trace_receiver_test.go

The original error message is extremely difficult to debug, for example (https://travis-ci.org/census-instrumentation/opencensus-service/builds/515417341#L1486):
```bash
Got:
[{identifier:<> library_info:<> service_info:<name:"issaTest" > attributes:<key:"bool" value:"true" > attributes:<key:"int64" value:"10000000" > attributes:<key:"string" value:"yes" >  <nil> [trace_id:"\001\002\003\004\005\006\007\010\t\n\013\014\r\016\017\200" span_id:"\257\256\255\254\253\252\251\250" parent_span_id:"\037\036\035\034\033\032\031\030" name:<value:"DBSearch" > start_time:<seconds:1542158650 nanos:536343000 > end_time:<seconds:1542159250 nanos:536343000 > attributes:<attribute_map:<key:"error" value:<bool_value:true > > attribute_map:<key:"status.code" value:<int_value:5 > > …
```

Use go-cmp to show the diff for test failures.

---

cmd/ocagent/main.go
internal/config/config.go
receiver/vmmetricsreceiver/.nocover
receiver/vmmetricsreceiver/doc.go
receiver/vmmetricsreceiver/example_config.yaml
receiver/vmmetricsreceiver/metrics_receiver.go
receiver/vmmetricsreceiver/transform_stats_to_metrics.go
receiver/vmmetricsreceiver/vm_metrics_collector.go
receiver/vmmetricsreceiver/vm_metrics_constants.go

Fixes https://github.com/census-instrumentation/opencensus-service/issues/514.
Only for POC purpose. Expose process and system telemetry and let users have access to it.

receiver: Add a prototype VM metrics receiver.

---

receiver/vmmetricsreceiver/example_config.yaml
receiver/vmmetricsreceiver/metrics_receiver.go
receiver/vmmetricsreceiver/vm_metrics_collector.go

In cases like when OC-Agent is running as a daemon set, the mount point of daemon set process may be different from the default one. Adding an option to allow users specify a different mount point for Agent process.

receiver/vmmetrics: Allow to have a different process mount point.

---

README.md
cmd/ocagent/config.yaml
exporter/stackdriverexporter/stackdriver.go

Fixes https://github.com/census-instrumentation/opencensus-service/issues/510
This will make it easier to create sample Kubernetes deployment configs for the agent for GCP, since the project ID won't need to be substituted into the exporter, but can just be left blank.
The `stackdriver.NewExporter` already defaults the project based on the GCP metadata if the project ID is set to the empty string, see this [code link](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/e393203a62e3c9286501f3195fe2f2ca1e35e115/stackdriver.go#L279)

Set default project when on GCP

---

Makefile

Use the general install-tools target so no one gets the vet failure if they follow the CONTRIBUTING.md instructions. Currently first attempt will fail with the download of go-cmp.

Add go-cmp to install-tools target

---

exporter/wavefrontexporter/.nocover
exporter/wavefrontexporter/README.md
exporter/wavefrontexporter/wavefront.go
exporter/wavefrontexporter/wavefront_test.go
go.mod
go.sum
internal/config/config.go

Add Wavefront exporter to agent.
This exporter currently uses `exporterwrapper` on the existing opencensus-go's `trace.Exporter` work from:
https://github.com/wavefrontHQ/opencensus-exporter
The above exporter supports exporting both traces and stats.
Sample usage is provided in README as a PR hasn't been opened for opencensus-website yet.
I've left the copyright/license lines blank as I was unsure. Above repo is Apache-2.0.
CC @songy23 @odeke-em

exporter: Add Wavefront exporter

---

PERFORMANCE.MD
README.md
cmd/occollector/app/builder/builder_test.go
cmd/occollector/app/builder/sampling_builder.go
cmd/occollector/app/builder/testdata/sampling_config.yaml
cmd/occollector/app/collector/processors.go
exporter/README.md
internal/collector/sampling/numeric_tag_filter.go
internal/collector/sampling/string_tag_filter.go

BREAKING CHANGE!!! Addresses #532
Changes:
* `numeric-tag-filter` > `numeric-attribute-filter`
* `string-tag-filter` > `string-attribute-filter`
* `tag` > `key`

Rename tail sampling tag as attribute

---

README.md
cmd/occollector/app/builder/processor_builder.go
cmd/occollector/app/builder/processor_builder_test.go
cmd/occollector/app/builder/testdata/global_attributes_all.yaml
cmd/occollector/app/builder/testdata/global_attributes_key_mapping.yaml
cmd/occollector/app/collector/processors.go
cmd/occollector/app/collector/processors_test.go
processor/attributekeyprocessor/attributekeyprocessor.go
processor/attributekeyprocessor/attributekeyprocessor_test.go

Many libraries and services didn't implement consistent naming for their span attribute keys, this feature provides the capability of making the attribute keys consistent for different libraries and services without the need to change their code.

Add span attribute key mapping support (#9)

---

go.mod
go.sum

Includes https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/148, which is the fix to https://github.com/census-instrumentation/opencensus-service/issues/542.

Update stackdriver exporter version.

---

internal/internal.go
internal/internal_test.go

Previously, multiple errors would produce a bunch of leading "; "s because `make` was called with a length rather than capacity and then was appended.
e.g. CombineErrors([foo bar]) = "[; ; foo; bar]"

Fix bug in internal.CombineErrors

---

internal/configmodels/configmodels.go
internal/configmodels/empty_test.go

This commit adds configuration models and is the first in the series of
planned commits that implement Configuration V2 support. For full support
of config V2 I plan to submit several additional PRs after this one is
reviewed and merged.
The next planned PR is the implementation of V2 configuration loading.
For reference, the Configuration Format V2 design doc:
https://docs.google.com/document/d/1GWOzV0H0RTN1adiwo7fTmkjfCATDDFGuOB4jp3ldCc8/edit#

Implement Configuration V2 models

---

internal/factories/factories.go
internal/factories/factories_test.go

The registry allows to register and retrieve factories for receivers, exporters and
processors by type. The factories will be used during configuration loading and during
pipeline building (only configuration related code is currently present, the rest
will be added gradually).
Testing done: automated tests.

Add global factory registry for receivers, exporters and processors

---

README.md
demos/trace/oc-agent-config.yaml
exporter/README.md
exporter/opencensusexporter/opencensus.go
exporter/opencensusexporter/opencensusexporter_test.go

Adding the new configuration settings now exposed by the oc-agent exporter:
- keepalive
- reconnection delay
Plus an option, secure, to use system cert pool (useful for https with well-known CAs).
The workers for OC exporter were being used in a round-robin fashion that didn't take into account that if one was already available, this is beneficial in the case in which a send operation takes much longer than the others.

OC exporter: new configuration settings and use first available worker

---

Makefile

Previously "vet" target was coded to fail if govet produced any output,
which is not a correct assumption. Govet can produce output even in
case of success [1]. The correct way to know if govet is successful is
to rely on exit code, which is exactly what is done now after this change.
[1] - see for example https://travis-ci.org/census-instrumentation/opencensus-service/builds/536550187

Fix "vet" target in makefile

---

internal/configv2/configv2.go
internal/configv2/configv2_test.go
internal/configv2/example_factories.go
internal/configv2/test_helpers.go
internal/factories/factories.go
internal/factories/factories_test.go
receiver/opencensusreceiver/config.go
receiver/opencensusreceiver/config_test.go
receiver/opencensusreceiver/factory.go
receiver/opencensusreceiver/factory_test.go
receiver/opencensusreceiver/testdata/config.yaml

- Added factory and config loading for OpenCensus receiver.
- Added support for custom unmarshaling of receiver configuration.
- Added ability for factory to create trace and metric receivers
based on configuration. This will be later required when building
the pipeline based on the config.
- Moved example factories used in tests to example_factories.go to
make it easier to reuse them in other tests.
Testing done: automated tests

Add implementation of OpenCensus receiver config

---

exporter/opencensusexporter/config.go
exporter/opencensusexporter/config_test.go
exporter/opencensusexporter/factory.go
exporter/opencensusexporter/factory_test.go
exporter/opencensusexporter/testdata/config.yaml

- Added factory and config loading for OpenCensus exporter.
Note: the factory is not compelte yet. We will need to add ability to
create the exporter based on its config. It will be done in a future PR.
Testing done: automated tests

Add implementation of OpenCensus exporter config

---

Makefile
cmd/occollector/app/builder/exporters_builder.go
cmd/occollector/app/builder/exporters_builder_test.go
cmd/occollector/app/collector/collector.go
cmd/occollector/app/collector/collector_test.go
cmd/occollector/app/collector/telemetry.go
cmd/occollector/app/collector/testdata/unisvc-config.yaml
cmd/unisvc/main.go
exporter/exporter.go
exporter/opencensusexporter/config_test.go
exporter/opencensusexporter/factory.go
exporter/opencensusexporter/factory_test.go
internal/configmodels/configmodels.go
internal/configv2/configv2.go
internal/configv2/configv2_test.go
internal/configv2/example_factories.go
internal/factories/factories.go
internal/factories/factories_test.go
unisvc/empty_test.go
unisvc/service.go

- Introduced a new unisvc binary and make target. Unisvc is
planned to be the implementation of the unified agent and collector
that uses the new configuration format.
- Refactored existing Application.execute() code to make it more
readable and also reusable.
The functionality is not changed. Reviews: please check this carefully!
- Introduced new Application.executeUnified() function that will call
all new agent/collector execution logic that is different from
old logic.
Application.executeUnified() is currently partial implementation,
which only builds the exporters. I plan to add building of processor
pipelines and receivers in future PRs.
- Introduced ExportersBuilder which builds runtime exporters based
on provided configuration.
- Added ability for App telemetry shutdown. This is …

Build exporters based on new configuration

---

go.mod
go.sum

upgade to get [fix](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/162) for copying resources when summary metrics is converted in SD exporter.

upgrade to stackdriver exporter v0.12.2

---

Makefile
go.mod
go.sum
tools/tools.go

From original change by @owais 
Reduces the set of install-tool dependencies and user the recommended to ensure that every build is using the same version of golint, we will have to manually update it when appropriate, but, this happens in a controlled fashion (ie.: no surprises by this being updated).
This way to control dependencies follows the recommendation at https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module on how to add tooling dependencies that was pointed by @owais.

Follow golang/wiki recommendation for tool dependencies and reduce install tools set

---

cmd/occollector/app/builder/exporters_builder.go
cmd/occollector/app/builder/exporters_builder_test.go
cmd/occollector/app/builder/pipelines_builder.go
cmd/occollector/app/builder/pipelines_builder_test.go
cmd/occollector/app/builder/testdata/pipelines_builder.yaml
cmd/occollector/app/collector/collector.go
cmd/occollector/app/collector/collector_test.go
consumer/consumer.go
internal/configmodels/configmodels.go
internal/configv2/configv2.go
internal/configv2/configv2_test.go
internal/configv2/example_factories.go
internal/testutils/testutils.go
processor/addattributesprocessor/config_test.go
processor/addattributesprocessor/factory.go
processor/processor.go
receiver/opencensusreceiver/factory_test.go

- Build pipeline processors and plug them into exporters.
- Added tests to verify that single exporter and multiple exporter pipelines
(fan out) work correctly.
- Minor cleanup in exporters_builder.go
- Fixed opencensus receiver TestCreateReceiver to find available port for
testing (instead of fixed port which would fail if already listened).

Build pipeline processors based on new configuration

---

README.md
cmd/occollector/app/builder/sampling_builder.go
cmd/occollector/app/collector/processors.go
cmd/occollector/app/collector/processors_test.go
processor/tracesamplerprocessor/tracesamplerprocessor.go
processor/tracesamplerprocessor/tracesamplerprocessor_test.go

This is to complete the sampling feature since OC Service already offers tail-sampling. This is implemented using an extra hashing as an attempt to avoid bias from trace ID generation and also to correctly spread traces for backends that also do hashing.

 Add trace head-sampling

---

go.mod
go.sum
receiver/vmmetricsreceiver/vm_metrics_collector.go

porting [changes](https://github.com/open-telemetry/opentelemetry-service/pull/31) from open-telemetry.
Porting it here because SD exporter is removed from otelsvc in opentelemetry-service (equivalent of OcAgent in opencensus-service.

add resource to vmreceiver

---

go.mod
go.sum

See https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/164 and https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/165.

Upgrade Stackdriver exporter version.

---

receiver/opencensusreceiver/ocmetrics/opencensus.go

When the grpc-gateway was added to this receiver/opencensus
Trace receiver in PR #270, we recognized that browsers
and other sources that send JSON in one burst won't stream
so would encounter an io.EOF. This PR makes the metrics
receiver replicates that behavior.
We'll get it this PR also ported over to the OpenTelemtry
service.
Fixes #610

receiver/opencensus/ocmetrics: ignore io.EOF on JSON upload

---

exporter/exporterwrapper/exporterwrapper.go
exporter/stackdriverexporter/stackdriver.go
exporter/stackdriverexporter/stackdriverexporter_test.go

This uses the `Language`, `CoreLibraryVersion` and `ExporterVersion` fields of the `LibraryInfo` message on `Node` to set the `g.co/agent` span label in the Stackdriver exporter.
Because this code is running in the OpenCensus service (agent/collector) it's safe to assume that the exporter type in the application library code must have been the `ocagent-exporter`. Hence, it sets the `g.co/agent` string as follows: `opencensus-[Language] [CoreLibraryVersion]; ocagent-exporter [ExporterVersion]`, e.g. `opencensus-python 0.0.1; ocagent-exporter 0.0.2`
Fixes https://github.com/census-instrumentation/opencensus-service/issues/525.

Set g.co/agent in Stackdriver exported via Node info

---

cmd/occollector/app/sender/jaeger_proto_grpc_sender.go
go.mod
go.sum

The exporter was essentially crashing itself unconditionally

Fixed Jaeger GRPC exporter
