cmd/opencensusd/main.go
=> Allow opencensusd to listen custom host:port

README.md
=> README: Add more specification on the first message.

interceptor/opencensus/opencensus.go, interceptor/opencensus/opencensus_test.go
Add multiplexing/"pass through" mode where spans from
sources other than the initiating node can be sent
and they should be properly proxied to their final
destination. This change also adds in tests to ensure
this behavior and to avoid regressions in the future.
Fixes #43
=> interceptor/opencensus: support multiplexing in Export

interceptor/opencensus/opencensus.go, interceptor/opencensus/opencensus_test.go
* Return immediately if the first message doesn't
have a non-nil Node. Previously we leniently
spun 15 times as a best case retry but that's
unnecessary
* If the first message is valid and has spans, those
spans MUST be consumed and NOT discarded.
Fixes #51
Fixes #53
=> interceptor/opencensus: fix protocol misreadings

README.md
Fixes https://github.com/census-instrumentation/opencensus-service/issues/54.
As I read through README, I found most of the old contents (especially the initiatives) are still relevant, so I just slightly modified the order of sections.
/cc @rakyll
=> README: re-organize the sections.

exporter/trace_exporter.go, interceptor/end_to_end_test.go, interceptor/opencensus/opencensus.go, interceptor/opencensus/opencensus_test.go, spanreceiver/spanreceiver.go
=> spanreceiver: update ReceiveSpans to take in a context.Context

.gitignore, Dockerfile, build_binaries.sh
=> build: added Dockerfile + binaries generator bash script

exporter/trace_exporter.go
=> exporter.TraceExporter: pass a context into ExportSpanData

internal/observability.go
=> exporter: add metrics recording helper for Exporters

README.md
Useful for navigating around the project but
also to have unique links.
=> README: add table of contents and link items

interceptor/opencensus/observability_test.go
The tests here unfortunately rely on the precise responses
of the stats worker i.e. view.SetReportingPeriod
However, with `go test -race`, `-race` instruments code
to find data races and slows the application down by a bit.
That therefore skews the expected precise timings and will
mean that by the time we compare our results, the worker
most likely is on the next cycle of exporting metrics which
produces flakes such as:
https://travis-ci.org/census-instrumentation/opencensus-service/builds/442325321
This change therefore just checks to ensure that all the
exported keys match and that the values are at least
len(wantTags) and still match exactly gotValues[:len(wantTags)]
=> interceptor/opencensus: fix flaky Observability test

translator/trace/protospan_to_spandata.go
From examining and comparing the Agent proto
vs the OpenCensus Go SpanData, discovered the
need to translate instead of only expecting
time events. Critical while examining differences
in the Zipkin interceptor.
=> translator/trace: add an Annotations translator

README.md, cmd/ocagent/config.go, cmd/ocagent/config.yaml, cmd/ocagent/main.go, exporter/exporterparser/zipkin.go, interceptor/opencensus/opencensus.go, interceptor/zipkin/testdata/sample1.json, interceptor/zipkin/trace_interceptor.go, interceptor/zipkin/trace_interceptor_test.go, internal/observability.go
Add Zipkin as a trace interceptor
Hooked the interceptor into cmd/ocagent
with a reporter by default "localhost:9412/api/v2/spans"
Fixes #24
=> interceptor: add zipkin /v2 interceptor

.github/wip.yml
This blocks merges when the PR is labeled or was a title with:
* "do not merge"
* "do not review"
* "WIP"
=> Enable WIP Tool

DESIGN.md, README.md
Fixes https://github.com/census-instrumentation/opencensus-service/issues/150.
=> document: move the design specs to DESIGN.md.

.travis.yml, Makefile, cmd/ocagent/config.go, exporter/exporterparser/datadog.go, exporter/exporterparser/exparser.go, exporter/exporterparser/jaeger.go, exporter/exporterparser/stackdriver.go, exporter/exporterparser/zipkin.go, exporter/trace_exporter.go, interceptor/interceptor.go, interceptor/opencensus/doc.go, interceptor/opencensus/opencensus.go, interceptor/opencensus/options.go, interceptor/opencensus/trace_interceptor.go, interceptor/zipkin/trace_interceptor.go, interceptor/zipkin/trace_interceptor_test.go, internal/internal.go, internal/observability.go, internal/version/version.go, metricsreceiver/metricsreceiver.go, spanreceiver/spanreceiver.go, translator/trace/protospan_to_spandata.go
Makes golint break the build and cleans up the existing issues so no
more are added to the repo.
Fix #159 
Closes #141
=> Clean up and enable golint

cmd/ocagent/main.go, cmd/occollector/main.go, exporter/example_test.go, exporter/trace_exporter.go, metricsink/sink.go, receiver/end_to_end_test.go, receiver/octrace/doc.go, receiver/octrace/opencensus.go, receiver/octrace/opencensus_test.go, receiver/octrace/options.go, receiver/octrace/trace_receiver.go, receiver/receiver.go, receiver/zipkin/trace_receiver.go, receiver/zipkin/trace_receiver_test.go, spansink/spansink.go
* spanreceiver.SpanReceiver -> spansink.Sink
* metricsreceiver.MetricsReceiver -> metricssink.Sink
Fixes #171
Follow-up of #166
=> spanreceiver.SpanReceiver->spansink.Sink, metricsreceiver.MetricsReceiver->metricsink.Sink

README.md
=> Output of ocagent

metricsink/sink.go, receiver/opencensus/ocmetrics/doc.go, receiver/opencensus/ocmetrics/opencensus.go, receiver/opencensus/ocmetrics/options.go, receiver/opencensus/octrace/observability_test.go, receiver/opencensus/octrace/opencensus.go, receiver/opencensus/opencensus.go
Updates https://github.com/census-instrumentation/opencensus-service/issues/136.
Next step: add observability and tests, then update cmd, config and README about ocmetrics configuration.
=> receiver/ocmetrics: start adding OCMetricsReceiver.

common/common.go, data/data.go
Updates https://github.com/census-instrumentation/opencensus-service/issues/215.
=> data: add TraceData and MetricsData.

receiver/opencensus/ocmetrics/opencensus_test.go
Updates https://github.com/census-instrumentation/opencensus-service/issues/225.
=> test: disable the flaky test for now.

README.md, exporter/exporterparser/ocagent.go, internal/config/config.go
Fixes https://github.com/census-instrumentation/opencensus-service/issues/248.
=> exporter: add ocagent exporter.

README.md, exporter/exporterparser/opencensus.go, internal/config/config.go
Fixes https://github.com/census-instrumentation/opencensus-service/issues/260.
=> exporter: rename ocagent -> opencensus

receiver/prometheus/doc.go, receiver/prometheus/metrics_receiver.go, receiver/prometheus/options.go
Updates https://github.com/census-instrumentation/opencensus-service/issues/137.
=> receiver/prometheus: start implementation.

README.md, exporter/exporterparser/README.md, receiver/README.md
Fixes the issues that I noticed on the README files.
=> Review of README files for beta

translator/trace/protospan_to_jaegerthrift.go, translator/trace/protospan_to_jaegerthrift_test.go, translator/trace/protospan_translation.go, translator/trace/testdata/thrift_batch_no_binary_tags_01.json
This was a pending TODO from some time ago. Fixes #305
=> Support MessageEvent and Annotation.Description from Proto to Jaeger

translator/trace/jaegerthrift_to_protospan_test.go, translator/trace/protospan_to_jaegerthrift.go
=> Fix duplicated span.kind in Jaeger sender

exporter/exporterparser/zipkin_test.go
The test depends on the 3 spans from the test data to arrive as a single batch. However, the zipkin exporter does not exposes this fine control of the zipkin reporter used to send the spans. In principle we could expose an option to adjust zipkin reporter batch size but that still requires the test to coordinate the send/receive of the batch. A simpler solution is to implement a mock of the zipkin reporter that behaves synchronously, avoiding any synchronization issue. This also avoids more API surface on the product code.
Fix #181 
Related to #375
=> Make TestZipkinExportersFromViper_roundtripJSON reliable

internal/compression/grpc/gzip.go
Hit this bug https://github.com/golang/lint/issues/366
=> Use import block for blank import.

README.md
There are few new flags that are not present on the README.
=> Update collector cli help on README

internal/collector/processor/processor.go, internal/collector/processor/queued/queued_processor.go
For more details read about Count aggregation (https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/DataAggregation.md).
=> Remove unnecessary recording for number of batches received/dropped.

processor/debug_processor.go, processor/debug_processor_test.go, processor/multi_processor.go, processor/multi_processor_test.go, processor/processor.go, processor/processortest/noop_processor.go, processor/processortest/noop_processor_test.go
After this we will replace:
* TraceReceiverSink -> TraceDataProcessor
* MetricsReceiverSink -> MetricsDataProcessor
* MetricsExporter -> MetricsDataProcessor
* TraceExporter -> TraceDataProcessor
* SpanProcessor -> TraceDataProcessor
=> Add unified interface for receiver/exporter/spanprocessor.

internal/internal.go
Just removing unused code from internal package.
=> Remove unused code in internal package

CONTRIBUTING.md
Adds the list of required tools to build from sources and so other minor changes to CONTRIBUTING.md
=> List required tools to build from sources

receiver/factorytemplate/factorytemplate.go, receiver/factorytemplate/factorytemplate_test.go
Opportunistic fix: renamed the files of factorytemplate package.
=> Add logger to construction methods.

internal/collector/processor/tailsampling/processor_test.go
The test seems to have been running in sequence on most (all?) of Travis runs: it makes assumptions about which traces will be present on idToTrace map and that is not possible when traces are added concurrently since there are no guarantees about the insertion order.
Fixed the concurrent test and added a sequential test in which the ids that are expected to have been dropped can be actually validated.
=> Fix test checking idToTrace map used in tail sampling

exporter/awsexporter/aws_xray.go, exporter/datadogexporter/datadog.go, exporter/exporterwrapper/exporterwrapper.go, exporter/honeycombexporter/honeycomb.go, exporter/jaegerexporter/jaeger.go, exporter/kafkaexporter/kafka.go, exporter/opencensusexporter/opencensus.go, exporter/stackdriverexporter/stackdriver.go
=> Update all exporters to use the new helper TraceExporter.

receiver/vmmetricsreceiver/vm_metrics_collector.go, receiver/vmmetricsreceiver/vm_metrics_constants.go
Also recording delta for sum aggregation by preserving previous values.
=> [WIP]fix aggregation type for per process stats and system stats.

Makefile, README.md, example/k8s.yaml
* Address #451
* Fix collector CLI documentation
* Update k8s example to latest standard
=> Update README and k8s.yaml example

internal/pprofserver/pprofserver.go, internal/pprofserver/pprofserver_test.go
As noticed by @sjkaris we need these two options to be set in order to use the mutex contention and blocking profiling modes of pprof.
=> Add profile fractions for Mutex and Block profiling

receiver/prometheusreceiver/metrics_receiver_test.go
Prometheus exporter has been migrated to consume `Metric` rather than `ViewData`. Fix this test by producing `Metric`s in the test.
=> receiver/prometheues: Fix test.

receiver/prometheusreceiver/metrics_receiver_test.go
See https://github.com/census-instrumentation/opencensus-service/pull/539#discussion_r280275515.
=> receiver/prometheus: ignore XXX_sizecache in test comparison.

PERFORMANCE.MD
=> Add initial OpenCensus exporter performance numbers

internal/factories/factories.go, receiver/jaegerreceiver/config.go, receiver/jaegerreceiver/config_test.go, receiver/jaegerreceiver/factory.go, receiver/jaegerreceiver/factory_test.go, receiver/jaegerreceiver/testdata/config.yaml
- Added factory and config loading for Jaeger receiver.
- Added ErrDataTypeIsNotSupported to factory definitions.
Testing done: automated tests
=> Add implementation of Jaeger receiver config

internal/configv2/example_factories.go, internal/factories/factories.go, internal/factories/factories_test.go, processor/addattributesprocessor/config.go, processor/addattributesprocessor/config_test.go, processor/addattributesprocessor/factory.go, processor/addattributesprocessor/factory_test.go, processor/addattributesprocessor/testdata/config.yaml
- Added factory and config loading for Attributes processor.
- Added ability to create processors in ProcessorFactory interface.
Testing done: automated tests
=> Add implementation of Attributes processor config

.github/CODEOWNERS
=> Add @rghetia to code owners

README.md
Make clear that the project is now in maintenance mode.
=> Add "maintenance mode" note to README

go.mod, go.sum, receiver/opencensusreceiver/opencensus.go, receiver/opencensusreceiver/opencensus_test.go
=> Add metrics service gRPC gateway. Upgrade deps.

README.md
There have been no changes in 2 years.
After this is merged, I will close issues and PRs, and archive the repository.
=> Mark repository as archived.
